<html xmlns="http://www.w3.org/1999/xhtml"
      style="margin:0 auto ;padding:0 ;height:100% ;width:100% ;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
<head
    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width"
          style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"
          style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
    <title
        style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
        index</title>

    <!-- Web Font / @font-face : BEGIN -->
    <!--[if mso]>
    <style>
        * {
            font-family: sans-serif !important;
        }
    </style>
    <![endif]-->
    <!--[if !mso]><!-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"
          style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
    <!--<![endif]-->

    <!-- Web Font / @font-face : END -->

    <!-- CSS Reset -->


    <!-- Progressive Enhancements -->


    <style type="text/css"
           style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
        html, body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }

        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
            font-family: 'Open Sans', sans-serif;
            line-height: 1.5em;
        }

        div[style*=margin:

        16
        px

        0
        ]
        {
            margin: 0 !important
        ;
        }
        table, td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }

        table table table {
            table-layout: auto;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        .mobile-link--footer a, a[x-apple-data-detectors] {
            color: #E9711C !important;
            text-decoration: none !important;
        }

        .button-td, .button-a {
            transition: all 100ms ease-in;
        }

        .button-td:hover, .button-a:hover {
            background: #555555 !important;
            border-color: #555555 !important;
        }

        @media screen and (max-width: 480px) {
            .fluid, .fluid-centered {
                width: 100% !important;
                max-width: 100% !important;
                height: auto !important;
                margin-left: auto !important;
                margin-right: auto !important;
            }

        }

        @media screen and (max-width: 480px) {
            .fluid-centered {
                margin-left: auto !important;
                margin-right: auto !important;
            }

        }

        @media screen and (max-width: 480px) {
            .stack-column, .stack-column-center {
                display: block !important;
                width: 100% !important;
                max-width: 100% !important;
                direction: ltr !important;
            }

        }

        @media screen and (max-width: 480px) {
            .stack-column-center {
                text-align: center !important;
            }

        }

        @media screen and (max-width: 480px) {
            .center-on-narrow {
                text-align: center !important;
                display: block !important;
                margin-left: auto !important;
                margin-right: auto !important;
                float: none !important;
            }

        }

        @media screen and (max-width: 480px) {
            table.center-on-narrow {
                display: inline-block !important;
            }

        }</style>
</head>
<body width="100%" bgcolor="#F7F7F7"
      style="margin:0 auto ;padding:0 ;height:100% ;width:100% ;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
<center
    style="width:100%;background:#F7F7F7;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">

    <div
        style="max-width:680px;margin:auto;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">

        <!-- Email Header : BEGIN -->
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%"
               style="max-width:680px;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;"
               role="presentation">
            <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                <td style="padding:40px;text-align:center;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                    <img src="https://ritense.com/wp-content/uploads/ritenselogovector.svg" width="200" height="50"
                         alt="Ritense Logo" border="0"
                         style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;-ms-interpolation-mode:bicubic;">
                </td>
            </tr>
        </table>
        <!-- Email Header : END -->

        <!-- Email Body : BEGIN -->

        <!-- 1 Column: BEGIN -->
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%"
               style="max-width:680px;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;"
               role="presentation">
            <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                <td bgcolor="#ffffff"
                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%"
                           style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;">
                        <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                            <td style="padding:40px;font-family:sans-serif;font-size:14px;mso-height-rule:exactly;line-height:1.5em;color:#686868;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                                <!-- Please Edit Content -->
                                <table cellspacing="0" cellpadding="0" border="0" width="100%"
                                       style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;">

                                    <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                        <td align="left" valign="top" width="100"
                                            style="font-weight:bold;font-family:'open sans':;, sans-serif:;font-size:14px;mso-height-rule:exactly;line-height:1.5em;color:#555555;vertical-align:top;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                                            Onderwerp
                                        </td>
                                        <td style="font-family:'open sans':;, sans-serif:;font-size:14px;mso-height-rule:exactly;line-height:1.5em;color:#555555;vertical-align:top;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                                            Task Send proposal to customer
                                        </td>
                                    </tr>

                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
        <!-- 1 Column : END -->

        <!-- 1 Column: BEGIN -->
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%"
               style="max-width:680px;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;"
               role="presentation">
            <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                <td bgcolor="#ffffff"
                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%"
                           style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;">
                        <!-- 1 Column: BEGIN -->
                        <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                            <td style="padding:40px;font-family:'open sans':;, sans-serif:;font-size:14px;mso-height-rule:exactly;line-height:1.5em;color:#555555;vertical-align:top;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                                <strong
                                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">Beste
                                    ${doc.firstName} ${doc.lastName}</strong>
                                <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;"><br
                                style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                Er is een taak aan u toegewezen. Gebruik de onderstaande link om de taak af te ronden:
                                <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                <a href="https://mandrillapp.com/track/click/30501861/ritense.test.valtimo.nl?p=eyJzIjoiVmV3UTk5T1ppNTBHQVAxU25hQldLOExrVUVFIiwidiI6MSwicCI6IntcInVcIjozMDUwMTg2MSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvcml0ZW5zZS50ZXN0LnZhbHRpbW8ubmxcXFwvI3Rhc2s_aWQ9YTgxMWExNzAtODA4OC0xMWVmLWE5ZGItMDI0MmFjMTEwMDAzXCIsXCJpZFwiOlwiMjJkMDRkNzE0MmQ0NDk5ZWJiYzVlYTc5ODAzZWE3MGJcIixcInVybF9pZHNcIjpbXCI5OGU1YmJlZTUzMjMzMzRkMzI4NjA2ODRkZTg2YzdhYjZlNmEwZWM5XCJdfSJ9"
                                   style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">Klik
                                    hier om de taak af te ronden</a>
                                <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                02/10/2024
                                <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                <strong
                                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">Met
                                    vriendelijke groet,<br
                                        style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">Ritense
                                    BPMN Team</strong>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">

        <!-- 1 Column: BEGIN -->
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%"
               style="max-width:680px;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;"
               role="presentation">
            <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                <td style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%"
                           style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;mso-table-lspace:0pt ;mso-table-rspace:0pt ;border-spacing:0 ;border-collapse:collapse ;table-layout:fixed ;margin:0 auto ;">
                        <tr style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                            <td style="padding:20px 40px;font-family:'open sans':;, sans-serif:;font-size:14px;mso-height-rule:exactly;line-height:1.5em;color:#555555;vertical-align:top;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;mso-table-lspace:0pt ;mso-table-rspace:0pt ;">
                                <strong
                                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">ritense
                                    b.v.</strong><br
                                style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                <span class="mobile-link--footer"
                                      style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">funenpark 1f<br
                                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">1018 ak amsterdam</span>
                                <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;"><br
                                style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                <span class="mobile-link--footer"
                                      style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;"><strong
                                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">algemeen</strong> +31203460800</span><br
                                style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                <span class="mobile-link--footer"
                                      style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;"><strong
                                    style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">support</strong> +31203460801</span><br
                                style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                                <a href="https://mandrillapp.com/track/click/30501861/www.ritense.com?p=eyJzIjoiMTBpTVNSRm1SUW1tUTJzdVlEMWhtSnZ3Q19FIiwidiI6MSwicCI6IntcInVcIjozMDUwMTg2MSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LnJpdGVuc2UuY29tXFxcL1wiLFwiaWRcIjpcIjIyZDA0ZDcxNDJkNDQ5OWViYmM1ZWE3OTgwM2VhNzBiXCIsXCJ1cmxfaWRzXCI6W1wiNjBmYmE1ZWNiYjQ1OTY0NGMzODYzMGRlM2IwZTAyYzUzNGY1NWEyMVwiXX0ifQ"
                                   style="color:#E9711C;text-decoration:none;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">www.ritense.com</a>
                                <br style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;"><br
                                style="-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-family:'Open Sans', sans-serif;line-height:1.5em;">
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <!-- 1 Column : END -->

        </table>
        <!-- Email Body : END -->


        <!--[if mso]>
        </td>
        </tr>
        </table>
        <![endif]-->
    </div>
</center>
<img src="https://mandrillapp.com/track/open.php?u=30501861&amp;id=22d04d7142d4499ebbc5ea79803ea70b" height="1"
     width="1" alt=""></body>
</html>

