/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.AanbodActiviteit
import com.inwonerplan.model.Subdoel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param naam 
 * @param aanbodActiviteiten 
 * @param subdoelen 
 * @param subdoel 
 * @param activiteiten 
 */


data class Aanbod (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "naam")
    val naam: kotlin.String? = null,

    @Json(name = "aanbodActiviteiten")
    val aanbodActiviteiten: kotlin.collections.List<AanbodActiviteit>? = null,

    @Json(name = "subdoelen")
    val subdoelen: kotlin.collections.List<Subdoel>? = null,

    @Json(name = "subdoel")
    val subdoel: kotlin.String? = null,

    @Json(name = "activiteiten")
    val activiteiten: kotlin.String? = null

)

