/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.Actiehouder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param codeaanbodactiviteit 
 * @param naamaanbodactiviteit 
 * @param actiehouder 
 * @param afhandeltermijn 
 * @param actief 
 * @param actiehouderlabel 
 */


data class AanbodActiviteit (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "codeaanbodactiviteit")
    val codeaanbodactiviteit: kotlin.String? = null,

    @Json(name = "naamaanbodactiviteit")
    val naamaanbodactiviteit: kotlin.String? = null,

    @Json(name = "actiehouder")
    val actiehouder: Actiehouder? = null,

    @Json(name = "afhandeltermijn")
    val afhandeltermijn: kotlin.Int? = null,

    @Json(name = "actief")
    val actief: kotlin.Boolean? = null,

    @Json(name = "actiehouderlabel")
    val actiehouderlabel: kotlin.String? = null

)

