/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.Actiehouder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actiehouder 
 * @param begindatum 
 * @param einddatum 
 * @param naam 
 * @param omschrijving 
 * @param status 
 * @param id 
 */


data class InwonerplanActiviteit (

    @Json(name = "actiehouder")
    val actiehouder: Actiehouder? = null,

    @Json(name = "begindatum")
    val begindatum: java.time.LocalDate? = null,

    @Json(name = "einddatum")
    val einddatum: java.time.LocalDate? = null,

    @Json(name = "naam")
    val naam: kotlin.String? = null,

    @Json(name = "omschrijving")
    val omschrijving: kotlin.String? = null,

    @Json(name = "status")
    val status: InwonerplanActiviteit.Status? = null,

    @Json(name = "id")
    val id: java.util.UUID? = null

) {

    /**
     * 
     *
     * Values: OPEN,AFGEROND
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "OPEN") OPEN("OPEN"),
        @Json(name = "AFGEROND") AFGEROND("AFGEROND");
    }
}

