/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.Kind

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param voornaam 
 * @param tussenvoegsel 
 * @param achternaam 
 * @param bsn 
 * @param telefoonnummer 
 * @param kinderen 
 */


data class InwonerProfiel (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "voornaam")
    val voornaam: kotlin.String? = null,

    @Json(name = "tussenvoegsel")
    val tussenvoegsel: kotlin.String? = null,

    @Json(name = "achternaam")
    val achternaam: kotlin.String? = null,

    @Json(name = "bsn")
    val bsn: kotlin.String? = null,

    @Json(name = "telefoonnummer")
    val telefoonnummer: kotlin.String? = null,

    @Json(name = "kinderen")
    val kinderen: kotlin.collections.List<Kind>? = null

)

