/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.InwonerplanHoofdDoel
import com.inwonerplan.model.InwonerplanSubdoel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uuid 
 * @param bsn 
 * @param hoofddoel 
 * @param subdoelen 
 */


data class InwonerPlan (

    @Json(name = "uuid")
    val uuid: java.util.UUID? = null,

    @Json(name = "bsn")
    val bsn: kotlin.String? = null,

    @Json(name = "hoofddoel")
    val hoofddoel: InwonerplanHoofdDoel? = null,

    @Json(name = "subdoelen")
    val subdoelen: kotlin.collections.List<InwonerplanSubdoel>? = null

)

