/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.InwonerplanActiviteit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param activiteiten 
 * @param aandachtspuntUUID 
 * @param subdoelUUID 
 */


data class InwonerplanSubdoel (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "activiteiten")
    val activiteiten: kotlin.collections.List<InwonerplanActiviteit>? = null,

    @Json(name = "aandachtspuntUUID")
    val aandachtspuntUUID: kotlin.String? = null,

    @Json(name = "subdoelUUID")
    val subdoelUUID: kotlin.String? = null

)

