/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param begindatum 
 * @param naamDoel 
 * @param id 
 */


data class InwonerplanHoofdDoel (

    @Json(name = "begindatum")
    val begindatum: java.time.LocalDate? = null,

    @Json(name = "naamDoel")
    val naamDoel: kotlin.String? = null,

    @Json(name = "id")
    val id: java.util.UUID? = null

)

