/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param voornaam 
 * @param tussenvoegsel 
 * @param achternaam 
 */


data class Kind (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "voornaam")
    val voornaam: kotlin.String? = null,

    @Json(name = "tussenvoegsel")
    val tussenvoegsel: kotlin.String? = null,

    @Json(name = "achternaam")
    val achternaam: kotlin.String? = null

)

