/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.inwonerplan.model

import com.inwonerplan.model.Aandachtspunt
import com.inwonerplan.model.Ontwikkelwens

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uuid 
 * @param code 
 * @param naam 
 * @param actief 
 * @param aandachtspuntenCodes 
 * @param aandachtspunten 
 * @param ontwikkelwensen 
 */


data class Subdoel (

    @Json(name = "uuid")
    val uuid: java.util.UUID? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "naam")
    val naam: kotlin.String? = null,

    @Json(name = "actief")
    val actief: kotlin.Boolean? = null,

    @Json(name = "aandachtspuntenCodes")
    val aandachtspuntenCodes: kotlin.String? = null,

    @Json(name = "aandachtspunten")
    val aandachtspunten: kotlin.collections.List<Aandachtspunt>? = null,

    @Json(name = "ontwikkelwensen")
    val ontwikkelwensen: kotlin.collections.List<Ontwikkelwens>? = null

)

