package com.ritense.temporaryresource.repository

import com.ritense.temporaryresource.domain.ResourceStorageMetadata
import com.ritense.temporaryresource.domain.ResourceStorageMetadataId
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface ResourceStorageMetadataRepository: JpaRepository<ResourceStorageMetadata, ResourceStorageMetadataId>