services:
    rabbitmq:
        image: rabbitmq:3-management
        volumes:
            - ../outbox/outbox-rabbitmq/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ../outbox/outbox-rabbitmq/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        ports:
            - "55672:5672"
    db:
        ports:
            - "3348:5432"
        environment:
            - POSTGRES_DB=outbox-rabbitmq-test