/*
 * Copyright 2015-2024 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ritense.processlink.domain

import com.fasterxml.jackson.annotation.JsonValue
import org.operaton.bpm.engine.delegate.ExecutionListener.EVENTNAME_END
import org.operaton.bpm.engine.delegate.ExecutionListener.EVENTNAME_START
import org.operaton.bpm.engine.delegate.TaskListener.EVENTNAME_ASSIGNMENT
import org.operaton.bpm.engine.delegate.TaskListener.EVENTNAME_COMPLETE
import org.operaton.bpm.engine.delegate.TaskListener.EVENTNAME_CREATE
import org.operaton.bpm.engine.delegate.TaskListener.EVENTNAME_DELETE
import org.operaton.bpm.engine.delegate.TaskListener.EVENTNAME_TIMEOUT
import org.operaton.bpm.engine.delegate.TaskListener.EVENTNAME_UPDATE
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_CANCEL as OPERATON_BOUNDARY_CANCEL
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_COMPENSATION as OPERATON_BOUNDARY_COMPENSATION
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_CONDITIONAL as OPERATON_BOUNDARY_CONDITIONAL
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_ERROR as OPERATON_BOUNDARY_ERROR
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_ESCALATION as OPERATON_BOUNDARY_ESCALATION
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_MESSAGE as OPERATON_BOUNDARY_MESSAGE
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_SIGNAL as OPERATON_BOUNDARY_SIGNAL
import org.operaton.bpm.engine.ActivityTypes.BOUNDARY_TIMER as OPERATON_BOUNDARY_TIMER
import org.operaton.bpm.engine.ActivityTypes.CALL_ACTIVITY as OPERATON_CALL_ACTIVITY
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_CANCEL as OPERATON_END_EVENT_CANCEL
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_COMPENSATION as OPERATON_END_EVENT_COMPENSATION
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_ERROR as OPERATON_END_EVENT_ERROR
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_ESCALATION as OPERATON_END_EVENT_ESCALATION
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_MESSAGE as OPERATON_END_EVENT_MESSAGE
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_NONE as OPERATON_END_EVENT_NONE
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_SIGNAL as OPERATON_END_EVENT_SIGNAL
import org.operaton.bpm.engine.ActivityTypes.END_EVENT_TERMINATE as OPERATON_END_EVENT_TERMINATE
import org.operaton.bpm.engine.ActivityTypes.GATEWAY_COMPLEX as OPERATON_GATEWAY_COMPLEX
import org.operaton.bpm.engine.ActivityTypes.GATEWAY_EVENT_BASED as OPERATON_GATEWAY_EVENT_BASED
import org.operaton.bpm.engine.ActivityTypes.GATEWAY_EXCLUSIVE as OPERATON_GATEWAY_EXCLUSIVE
import org.operaton.bpm.engine.ActivityTypes.GATEWAY_INCLUSIVE as OPERATON_GATEWAY_INCLUSIVE
import org.operaton.bpm.engine.ActivityTypes.GATEWAY_PARALLEL as OPERATON_GATEWAY_PARALLEL
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_CATCH as OPERATON_INTERMEDIATE_EVENT_CATCH
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_COMPENSATION_THROW as OPERATON_INTERMEDIATE_EVENT_COMPENSATION_THROW
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_CONDITIONAL as OPERATON_INTERMEDIATE_EVENT_CONDITIONAL
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_ESCALATION_THROW as OPERATON_INTERMEDIATE_EVENT_ESCALATION_THROW
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_LINK as OPERATON_INTERMEDIATE_EVENT_LINK
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_MESSAGE as OPERATON_INTERMEDIATE_EVENT_MESSAGE
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_MESSAGE_THROW as OPERATON_INTERMEDIATE_EVENT_MESSAGE_THROW
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_NONE_THROW as OPERATON_INTERMEDIATE_EVENT_NONE_THROW
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_SIGNAL as OPERATON_INTERMEDIATE_EVENT_SIGNAL
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_SIGNAL_THROW as OPERATON_INTERMEDIATE_EVENT_SIGNAL_THROW
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_THROW as OPERATON_INTERMEDIATE_EVENT_THROW
import org.operaton.bpm.engine.ActivityTypes.INTERMEDIATE_EVENT_TIMER as OPERATON_INTERMEDIATE_EVENT_TIMER
import org.operaton.bpm.engine.ActivityTypes.MULTI_INSTANCE_BODY as OPERATON_MULTI_INSTANCE_BODY
import org.operaton.bpm.engine.ActivityTypes.START_EVENT as OPERATON_START_EVENT
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_COMPENSATION as OPERATON_START_EVENT_COMPENSATION
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_CONDITIONAL as OPERATON_START_EVENT_CONDITIONAL
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_ERROR as OPERATON_START_EVENT_ERROR
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_ESCALATION as OPERATON_START_EVENT_ESCALATION
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_MESSAGE as OPERATON_START_EVENT_MESSAGE
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_SIGNAL as OPERATON_START_EVENT_SIGNAL
import org.operaton.bpm.engine.ActivityTypes.START_EVENT_TIMER as OPERATON_START_EVENT_TIMER
import org.operaton.bpm.engine.ActivityTypes.SUB_PROCESS as OPERATON_SUB_PROCESS
import org.operaton.bpm.engine.ActivityTypes.SUB_PROCESS_AD_HOC as OPERATON_SUB_PROCESS_AD_HOC
import org.operaton.bpm.engine.ActivityTypes.TASK as OPERATON_TASK
import org.operaton.bpm.engine.ActivityTypes.TASK_BUSINESS_RULE as OPERATON_TASK_BUSINESS_RULE
import org.operaton.bpm.engine.ActivityTypes.TASK_MANUAL_TASK as OPERATON_TASK_MANUAL_TASK
import org.operaton.bpm.engine.ActivityTypes.TASK_RECEIVE_TASK as OPERATON_TASK_RECEIVE_TASK
import org.operaton.bpm.engine.ActivityTypes.TASK_SCRIPT as OPERATON_TASK_SCRIPT
import org.operaton.bpm.engine.ActivityTypes.TASK_SEND_TASK as OPERATON_TASK_SEND_TASK
import org.operaton.bpm.engine.ActivityTypes.TASK_SERVICE as OPERATON_TASK_SERVICE
import org.operaton.bpm.engine.ActivityTypes.TASK_USER_TASK as OPERATON_TASK_USER_TASK
import org.operaton.bpm.engine.ActivityTypes.TRANSACTION as OPERATON_TRANSACTION

enum class ActivityTypeWithEventName(
    @JsonValue val value: String
) {
    MULTI_INSTANCE_BODY_START(getActivityTypeWithEventNameValue(OPERATON_MULTI_INSTANCE_BODY, EVENTNAME_START)),
    MULTI_INSTANCE_BODY_END(getActivityTypeWithEventNameValue(OPERATON_MULTI_INSTANCE_BODY, EVENTNAME_END)),

    EXCLUSIVE_GATEWAY_START(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_EXCLUSIVE, EVENTNAME_START)),
    EXCLUSIVE_GATEWAY_END(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_EXCLUSIVE, EVENTNAME_END)),

    INCLUSIVE_GATEWAY_START(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_INCLUSIVE, EVENTNAME_START)),
    INCLUSIVE_GATEWAY_END(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_INCLUSIVE, EVENTNAME_END)),

    PARALLEL_GATEWAY_START(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_PARALLEL, EVENTNAME_START)),
    PARALLEL_GATEWAY_END(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_PARALLEL, EVENTNAME_END)),

    COMPLEX_GATEWAY_START(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_COMPLEX, EVENTNAME_START)),
    COMPLEX_GATEWAY_END(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_COMPLEX, EVENTNAME_END)),

    EVENT_BASED_GATEWAY_START(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_EVENT_BASED, EVENTNAME_START)),
    EVENT_BASED_GATEWAY_END(getActivityTypeWithEventNameValue(OPERATON_GATEWAY_EVENT_BASED, EVENTNAME_END)),


    TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK, EVENTNAME_START)),
    TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK, EVENTNAME_END)),

    SCRIPT_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_SCRIPT, EVENTNAME_START)),
    SCRIPT_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_SCRIPT, EVENTNAME_END)),

    SERVICE_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_SERVICE, EVENTNAME_START)),
    SERVICE_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_SERVICE, EVENTNAME_END)),

    BUSINESS_RULE_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_BUSINESS_RULE, EVENTNAME_START)),
    BUSINESS_RULE_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_BUSINESS_RULE, EVENTNAME_END)),

    MANUAL_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_MANUAL_TASK, EVENTNAME_START)),
    MANUAL_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_MANUAL_TASK, EVENTNAME_END)),

    USER_TASK_CREATE(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_CREATE)),
    USER_TASK_ASSIGNMENT(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_ASSIGNMENT)),
    USER_TASK_COMPLETE(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_COMPLETE)),
    USER_TASK_UPDATE(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_UPDATE)),
    USER_TASK_DELETE(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_DELETE)),
    USER_TASK_TIMEOUT(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_TIMEOUT)),

    USER_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_START)),
    USER_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_USER_TASK, EVENTNAME_END)),

    SEND_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_SEND_TASK, EVENTNAME_START)),
    SEND_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_SEND_TASK, EVENTNAME_END)),

    RECEIVE_TASK_START(getActivityTypeWithEventNameValue(OPERATON_TASK_RECEIVE_TASK, EVENTNAME_START)),
    RECEIVE_TASK_END(getActivityTypeWithEventNameValue(OPERATON_TASK_RECEIVE_TASK, EVENTNAME_END)),


    SUB_PROCESS_START(getActivityTypeWithEventNameValue(OPERATON_SUB_PROCESS, EVENTNAME_START)),
    SUB_PROCESS_END(getActivityTypeWithEventNameValue(OPERATON_SUB_PROCESS, EVENTNAME_END)),

    AD_HOC_SUB_PROCESS_START(getActivityTypeWithEventNameValue(OPERATON_SUB_PROCESS_AD_HOC, EVENTNAME_START)),
    AD_HOC_SUB_PROCESS_END(getActivityTypeWithEventNameValue(OPERATON_SUB_PROCESS_AD_HOC, EVENTNAME_END)),

    CALL_ACTIVITY_START(getActivityTypeWithEventNameValue(OPERATON_CALL_ACTIVITY, EVENTNAME_START)),
    CALL_ACTIVITY_END(getActivityTypeWithEventNameValue(OPERATON_CALL_ACTIVITY, EVENTNAME_END)),

    TRANSACTION_START(getActivityTypeWithEventNameValue(OPERATON_TRANSACTION, EVENTNAME_START)),
    TRANSACTION_END(getActivityTypeWithEventNameValue(OPERATON_TRANSACTION, EVENTNAME_END)),


    BOUNDARY_TIMER_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_TIMER, EVENTNAME_START)),
    BOUNDARY_TIMER_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_TIMER, EVENTNAME_END)),

    BOUNDARY_MESSAGE_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_MESSAGE, EVENTNAME_START)),
    BOUNDARY_MESSAGE_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_MESSAGE, EVENTNAME_END)),

    BOUNDARY_SIGNAL_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_SIGNAL, EVENTNAME_START)),
    BOUNDARY_SIGNAL_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_SIGNAL, EVENTNAME_END)),

    COMPENSATION_BOUNDARY_CATCH_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_COMPENSATION, EVENTNAME_START)),
    COMPENSATION_BOUNDARY_CATCH_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_COMPENSATION, EVENTNAME_END)),

    BOUNDARY_ERROR_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_ERROR, EVENTNAME_START)),
    BOUNDARY_ERROR_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_ERROR, EVENTNAME_END)),

    BOUNDARY_ESCALATION_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_ESCALATION, EVENTNAME_START)),
    BOUNDARY_ESCALATION_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_ESCALATION, EVENTNAME_END)),

    CANCEL_BOUNDARY_CATCH_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_CANCEL, EVENTNAME_START)),
    CANCEL_BOUNDARY_CATCH_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_CANCEL, EVENTNAME_END)),

    BOUNDARY_CONDITIONAL_START(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_CONDITIONAL, EVENTNAME_START)),
    BOUNDARY_CONDITIONAL_END(getActivityTypeWithEventNameValue(OPERATON_BOUNDARY_CONDITIONAL, EVENTNAME_END)),


    START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT, EVENTNAME_START)),
    START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT, EVENTNAME_END)),

    START_TIMER_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_TIMER, EVENTNAME_START)),
    START_TIMER_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_TIMER, EVENTNAME_END)),

    MESSAGE_START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_MESSAGE, EVENTNAME_START)),
    MESSAGE_START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_MESSAGE, EVENTNAME_END)),

    SIGNAL_START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_SIGNAL, EVENTNAME_START)),
    SIGNAL_START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_SIGNAL, EVENTNAME_END)),

    ESCALATION_START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_ESCALATION, EVENTNAME_START)),
    ESCALATION_START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_ESCALATION, EVENTNAME_END)),

    COMPENSATION_START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_COMPENSATION, EVENTNAME_START)),
    COMPENSATION_START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_COMPENSATION, EVENTNAME_END)),

    ERROR_START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_ERROR, EVENTNAME_START)),
    ERROR_START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_ERROR, EVENTNAME_END)),

    CONDITIONAL_START_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_CONDITIONAL, EVENTNAME_START)),
    CONDITIONAL_START_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_START_EVENT_CONDITIONAL, EVENTNAME_END)),


    INTERMEDIATE_CATCH_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_CATCH, EVENTNAME_START)),
    INTERMEDIATE_CATCH_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_CATCH, EVENTNAME_END)),

    INTERMEDIATE_MESSAGE_CATCH_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_MESSAGE, EVENTNAME_START)),
    INTERMEDIATE_MESSAGE_CATCH_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_MESSAGE, EVENTNAME_END)),

    INTERMEDIATE_TIMER_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_TIMER, EVENTNAME_START)),
    INTERMEDIATE_TIMER_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_TIMER, EVENTNAME_END)),

    INTERMEDIATE_LINK_CATCH_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_LINK, EVENTNAME_START)),
    INTERMEDIATE_LINK_CATCH_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_LINK, EVENTNAME_END)),

    INTERMEDIATE_SIGNAL_CATCH_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_SIGNAL, EVENTNAME_START)),
    INTERMEDIATE_SIGNAL_CATCH_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_SIGNAL, EVENTNAME_END)),

    INTERMEDIATE_CONDITIONAL_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_CONDITIONAL, EVENTNAME_START)),
    INTERMEDIATE_CONDITIONAL_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_CONDITIONAL, EVENTNAME_END)),

    INTERMEDIATE_THROW_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_THROW, EVENTNAME_START)),
    INTERMEDIATE_THROW_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_THROW, EVENTNAME_END)),

    INTERMEDIATE_SIGNAL_THROW_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_SIGNAL_THROW, EVENTNAME_START)),
    INTERMEDIATE_SIGNAL_THROW_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_SIGNAL_THROW, EVENTNAME_END)),

    INTERMEDIATE_COMPENSATION_THROW_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_COMPENSATION_THROW, EVENTNAME_START)),
    INTERMEDIATE_COMPENSATION_THROW_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_COMPENSATION_THROW, EVENTNAME_END)),

    INTERMEDIATE_MESSAGE_THROW_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_MESSAGE_THROW, EVENTNAME_START)),
    INTERMEDIATE_MESSAGE_THROW_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_MESSAGE_THROW, EVENTNAME_END)),

    INTERMEDIATE_NONE_THROW_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_NONE_THROW, EVENTNAME_START)),
    INTERMEDIATE_NONE_THROW_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_NONE_THROW, EVENTNAME_END)),

    INTERMEDIATE_ESCALATION_THROW_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_ESCALATION_THROW, EVENTNAME_START)),
    INTERMEDIATE_ESCALATION_THROW_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_INTERMEDIATE_EVENT_ESCALATION_THROW, EVENTNAME_END)),


    ERROR_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_ERROR, EVENTNAME_START)),
    ERROR_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_ERROR, EVENTNAME_END)),

    CANCEL_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_CANCEL, EVENTNAME_START)),
    CANCEL_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_CANCEL, EVENTNAME_END)),

    TERMINATE_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_TERMINATE, EVENTNAME_START)),
    TERMINATE_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_TERMINATE, EVENTNAME_END)),

    MESSAGE_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_MESSAGE, EVENTNAME_START)),
    MESSAGE_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_MESSAGE, EVENTNAME_END)),

    SIGNAL_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_SIGNAL, EVENTNAME_START)),
    SIGNAL_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_SIGNAL, EVENTNAME_END)),

    COMPENSATION_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_COMPENSATION, EVENTNAME_START)),
    COMPENSATION_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_COMPENSATION, EVENTNAME_END)),

    ESCALATION_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_ESCALATION, EVENTNAME_START)),
    ESCALATION_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_ESCALATION, EVENTNAME_END)),

    NONE_END_EVENT_START(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_NONE, EVENTNAME_START)),
    NONE_END_EVENT_END(getActivityTypeWithEventNameValue(OPERATON_END_EVENT_NONE, EVENTNAME_END));


    companion object {
        private val mapping = entries.associateBy(ActivityTypeWithEventName::value)
        fun fromValue(value: String) = mapping[value] ?: error("Can't find ActivityTypeWithEventName with value $value")
        fun contains(value: String): Boolean = mapping[value] != null
    }
}

private fun getActivityTypeWithEventNameValue(activityType: String, eventName: String): String {
    return "bpmn:" + activityType.replaceFirstChar { it.uppercaseChar() } + ":" + eventName
}
