version: '3.9'
services:
    database:
        image: mysql:8.0.31
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: valtimo-implementation-dev
            MYSQL_USER: valtimo
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        command: [
            "--default-authentication-plugin=mysql_native_password",
            "--lower_case_table_names=1",
            "--collation-server=utf8mb4_unicode_ci",
            "--character-set-server=utf8mb4",
            "--explicit_defaults_for_timestamp",
            "--ssl=false",
            "--innodb_flush_method=O_DIRECT",
            "--sql_mode=NO_ENGINE_SUBSTITUTION"
        ]
        volumes:
            - mysql-database-data:/var/lib/mysql # persist data even if container shuts down
volumes:
    mysql-database-data: # named volumes can be managed easier using docker-compose