version: '3.9'
services:
    db:
        image: mysql:8.3.0
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        command:
            --information-schema-stats-expiry=0
            --innodb-flush-method=O_DIRECT
            --lower-case-table-names=1
            --sql-mode=NO_ENGINE_SUBSTITUTION
        #ports:
           # - "5432:5432" #needs overriding "XXXX:5432" XXXX=your-own-port-per-module-test
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: valtimo #needs overriding
            MYSQL_USER: valtimo
            MYSQL_PASSWORD: password
# Ports taken
#   url: jdbc:mysql://localhost:3301/form-test
#   url: jdbc:mysql://localhost:3302/form-test-link
#   url: jdbc:mysql://localhost:3303/document-test
#   url: jdbc:mysql://localhost:3304/core-test
#   url: jdbc:mysql://localhost:3305/connector-test
#   url: jdbc:mysql://localhost:3307/audit-test
#   url: jdbc:mysql://localhost:3308/objects-api-test
#   url: jdbc:mysql://localhost:3309/openzaak-test
#   url: jdbc:mysql://localhost:3310/process-document-test
#   url: jdbc:mysql://localhost:3311/s3-resource-test
#   url: jdbc:mysql://localhost:3312/reporting-cloud-test
#   url: jdbc:mysql://localhost:3313/milestones-test
#   url: jdbc:mysql://localhost:3314/mail-test
#   url: jdbc:mysql://localhost:3315/contactmoment-test
#   url: jdbc:mysql://localhost:3316/wordpress-mail-test
#   url: jdbc:mysql://localhost:3317/smartdocuments-test
#   url: jdbc:mysql://localhost:3318/besluit-test
#   url: jdbc:mysql://localhost:3319/haalcentraal-brp-test
#   url: jdbc:mysql://localhost:3320/form-flow-valtimo-test
#   url: jdbc:mysql://localhost:3321/form-flow-test
#   url: jdbc:mysql://localhost:3322/plugin-test
#   url: jdbc:mysql://localhost:3323/value-resolver-test
#   url: jdbc:mysql://localhost:3324/documenten-api-test
#   url: jdbc:mysql://localhost:3325/zaken-api-test
#   url: jdbc:mysql://localhost:3326/notes-test
#   url: jdbc:mysql://localhost:3327/klant-test
#   url: jdbc:mysql://localhost:3328/objecten-api-authentication-test
#   url: jdbc:mysql://localhost:3329/objecttypen-api-test
#   url: jdbc:mysql://localhost:3330/objecten-api-test
#   url: jdbc:mysql://localhost:3331/flowmailer-test
#   url: jdbc:mysql://localhost:3332/case-test
#   url: jdbc:mysql://localhost:3333/object-manegement-test
#   url: jdbc:mysql://localhost:3334/notificaties-api-test
#   url: jdbc:mysql://localhost:3335/notificaties-api-authentication-test
#   url: jdbc:mysql://localhost:3336/plugin-valtimo-test
#   url: jdbc:mysql://localhost:3337/verzoek-test
#   url: jdbc:mysql://localhost:3338/portaaltaak-test
#   url: jdbc:mysql://localhost:3339/dataprovider-test
#   url: jdbc:mysql://localhost:3341/search-test
#   url: jdbc:mysql://localhost:3342/process-link-test
#   url: jdbc:mysql://localhost:3343/dashboard-test
#   url: jdbc:mysql://localhost:3344/authorization
#   url: jdbc:mysql://localhost:3345/changelog-test
#   url: jdbc:mysql://localhost:3346/contract-test
#   url: jdbc:mysql://localhost:3347/outbox-test
#   url: jdbc:mysql://localhost:3348/outbox-rabbitmq-test
#   url: jdbc:mysql://localhost:3349/localization-test
#   url: jdbc:mysql://localhost:3351/zaakdetails-test
#   url: localhost:55672 <--rabbitmq
