version: '3.9'
services:
    database-objects-api-test:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: objects-api-test
            MYSQL_USER: valtimo
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        command: [
            "--default-authentication-plugin=mysql_native_password",
            "--lower_case_table_names=1",
            "--collation-server=utf8mb4_unicode_ci",
            "--character-set-server=utf8mb4",
            "--explicit_defaults_for_timestamp",
            "--ssl=false",
            "--innodb_flush_method=O_DIRECT",
            "--sql_mode=NO_ENGINE_SUBSTITUTION"
        ]