spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/valtimo-core-db
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql

valtimo:
    database: postgres

camunda:
    bpm:
        database:
            type: postgres