spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5444/gzac-core-db
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

camunda:
    bpm:
        database:
            type: postgres

valtimo:
    database: postgres