spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5444/gzac-core-db
        hikari:
            data-source-properties:
              stringtype: unspecified
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect



valtimo:
    database: postgres