version: '3.9'
services:
    rabbitmq:
        image: rabbitmq:3-management
        volumes:
            - ../outbox/outbox-rabbitmq/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ../outbox/outbox-rabbitmq/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        ports:
            - "55673:5672"